default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456tmc
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: delivery_development

test:
  <<: *default
  database: delivery_test

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 15
